name: Cpp

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: get_cppcheck
      run: sudo apt-get -y install cppcheck
    - name: Code Quality
      run: make analysis 3_Implementation/
